version: "3"

services:
  test_db:
    container_name: 'test_db'
    image: 'postgres:12.6-alpine'
    restart: always
    env_file:
      - .env.test
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_server:
    build: .
    entrypoint: /bin/sh './scripts/test-setup.sh'
    env_file:
      - .env.test
    ports:
      - '3030:3030'
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      test_db:
        condition: service_healthy
    links:
      - test_db
    container_name: 'test_server'
    volumes:
      - .:/app/
