name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: format
        run: yarn prettier -c .
      - name: test
        run: |
          yarn && yarn test
          echo "exit code $?"
          if [ $? -ne 0 ]; then
            exit 1
          fi